name: Hello World!

on: 
  push:
    branches: 
      - 'master'
      - 'failing-tests'
      - 'fail-tests2'
      - 'fail-tests3'
  pull_request:
    branches:
      - 'main'
      - 'fail-tests3'

jobs: 
  hello: 
    runs-on: ubuntu-latest

    steps:
      - name: Hello Step
        run: echo "Hello World"
